//@ui5-bundle com/myorg/myapp/Component-preload.js
sap.ui.require.preload({
	"com/myorg/myapp/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device"],function(t,n){const s=n["support"];const i=t.extend("com.myorg.myapp.Component",{metadata:{manifest:"json"},init:function n(){t.prototype.init.call(this)},getContentDensityClass:function t(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.contentDensityClass=""}else if(!s.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}});return i});
},
	"com/myorg/myapp/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){const t=e.extend("com.myorg.myapp.controller.AppController",{onInit:function e(){this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass());const t=this.getView().byId("myList");const n=t.getItems()[0];n.setSelected(true);this.handleSelectionChange(undefined,n)},handleSelectionChange:function e(t,n){if(t){alert(t.getParameter("listItem").getId())}else{const e=n.getId();alert(e)}}});return t});
},
	"com/myorg/myapp/i18n/i18n.properties":'app_title=myapp\napp_description=UI5 Application myapp\nbtn_text=Say Hello',
	"com/myorg/myapp/i18n/i18n_de.properties":'app_title=myapp\napp_description=UI5 Application myapp\nbtn_text=Sag Hallo',
	"com/myorg/myapp/i18n/i18n_en.properties":'app_title=myapp\napp_description=UI5 Application myapp\nbtn_text=Say Hello',
	"com/myorg/myapp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.myorg.myapp","type":"application","i18n":"i18n/i18n.properties","title":"{{app_title}}","description":"{{app_description}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"com.myorg.myapp.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.95.0","libs":{"sap.ui.core":{},"sap.ui.layout":{},"sap.ui.unified":{},"sap.m":{}}},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.myorg.myapp.i18n.i18n"}}},"routing":{}}}',
	"com/myorg/myapp/view/App.view.xml":'<mvc:View\n\tcontrollerName="com.myorg.myapp.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><App id="app"><Page><List id="myList" headerText="My List"\n\t\t\t\tmode="MultiSelect"\n\t\t\t\tselectionChange=".handleSelectionChange"><items><StandardListItem title="The title" description="The Description" type="Navigation"></StandardListItem><StandardListItem title="The title" description="The Description" type="Navigation"></StandardListItem></items></List></Page></App></mvc:View>'
});
